name: Deploy Static Website to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia si usas otra rama para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh-pages           # rama donde se publica
          publish_dir: ./                    # carpeta raíz con index.html
          user_name: 'github-actions[bot]'  # opcional para commit author
          user_email: 'github-actions[bot]@users.noreply.github.com'
          keep_files: false                  # elimina archivos previos para evitar basura
