name: Deploy Static Website to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia si usas otra rama para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./  # raíz del repo, donde está index.html
